language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 5.4
    - php: 5.5
    - php: hhvm

before_script:
  - composer self-update
  - composer install

script: ./vendor/bin/tester -p php -c ./tests/php.ini-unix ./tests/

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'